static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 80
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                access_log:
                  - name: envoy.file_access_log
                    config:
                      path: /data/logs/lesscode-usercenter/envoy.log
                      json_format: {"jsonType":"accessLog","name":"lesscode-usercenter","tag":"envoy","startTime":"%START_TIME%","method":"%REQ(:METHOD)%","path":"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%","bytesReceived":"%BYTES_RECEIVED%","protocol":"%PROTOCOL%","userAgent":"%REQ(USER-AGENT)%","forwardedFor":"%REQ(X-FORWARDED-FOR)%","requestId":"%REQ(X-REQUEST-ID)%","pmTraceId":"%REQ(PM-TRACE-ID)%","authority":"%REQ(:AUTHORITY)%","responseCode":"%RESPONSE_CODE%","responseCodeDetails":"%RESPONSE_CODE_DETAILS%","bytesSent":"%BYTES_SENT%","duration":"%DURATION%","responseDuration":"%RESPONSE_DURATION%","responseEnvoyUpstreamServiceTime":"%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%","responseTxDuration":"%RESPONSE_TX_DURATION%","upstreamHost":"%UPSTREAM_HOST%","upstreamCluster":"%UPSTREAM_CLUSTER%","upstreamLocalAddress":"%UPSTREAM_LOCAL_ADDRESS%","downstreamRemoteAddress":"%DOWNSTREAM_REMOTE_ADDRESS%","downstreamRemoteAddressWithoutPort":"%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%","downstreamLocalAddress":"%DOWNSTREAM_LOCAL_ADDRESS%","downStreamLocalAddressWithoutPort":"%DOWNSTREAM_LOCAL_ADDRESS_WITHOUT_PORT%"}
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: local_service
                http_filters:
                  - name: envoy.router
                    typed_config: {}
  clusters:
    - name: local_service
      connect_timeout: 0.25s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: local_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 15001
admin:
  access_log_path: "/data/logs/lesscode-usercenter/admin.log"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8081
