// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package vo

import (
	"github.com/star-table/usercenter/core/types"
)

type BasicConfigResp struct {
	// 运行模式，1：Saas集群，2：单机部署，3：私有化集群部署，4：私有化单库部署
	RunMode int `json:"runMode"`
	// 构建信息
	BuildInfo *BuildInfoDefine `json:"buildInfo"`
}

type BuildInfoDefine struct {
	GitCommitLog   string `json:"gitCommitLog"`
	GitStatus      string `json:"gitStatus"`
	BuildTime      string `json:"buildTime"`
	BuildGoVersion string `json:"buildGoVersion"`
}

type ChatData struct {
	// 群聊id
	OutChatID string `json:"outChatId"`
	// 群聊名称
	Name string `json:"name"`
	// 群聊描述
	Description *string `json:"description"`
	// 关联id(关联列表时有)
	RelationID *int64 `json:"relationId"`
	// 群聊头像
	Avatar string `json:"avatar"`
	// 是否是项目主群
	IsMain bool `json:"isMain"`
}

type ChatListResp struct {
	// 数量
	Total int64 `json:"total"`
	// 列表
	List []*ChatData `json:"list"`
}

// 创建接入应用信息请求结构体
type CreateAppInfoReq struct {
	// 名称
	Name string `json:"name"`
	// 应用编号
	Code string `json:"code"`
	// 秘钥1
	Secret1 string `json:"secret1"`
	// 秘钥2
	Secret2 string `json:"secret2"`
	// 负责人
	Owner string `json:"owner"`
	// 审核状态,1待审核,2审核通过,3审核未通过
	CheckStatus int `json:"checkStatus"`
	// 状态,  1可用,2禁用
	Status int `json:"status"`
	// 创建人
	Creator int64 `json:"creator"`
	// 创建时间
	CreateTime types.Time `json:"createTime"`
	// 更新人
	Updator int64 `json:"updator"`
	// 更新时间
	UpdateTime types.Time `json:"updateTime"`
	// 乐观锁
	Version int `json:"version"`
	// 是否删除,1是,2否
	IsDelete int `json:"isDelete"`
}

// 创建部门请求结构体
type CreateDepartmentReq struct {
	// 组织id
	OrgID int64 `json:"orgId"`
	// 部门名称
	Name string `json:"name"`
	// 部门标识
	Code string `json:"code"`
	// 父部门id
	ParentID int64 `json:"parentId"`
	// 排序
	Sort int `json:"sort"`
	// 是否隐藏部门,1隐藏,2不隐藏
	IsHide int `json:"isHide"`
	// 来源渠道,
	SourceChannel string `json:"sourceChannel"`
	// 状态, 1可用,2禁用
	Status int `json:"status"`
	// 创建人
	Creator int64 `json:"creator"`
	// 创建时间
	CreateTime types.Time `json:"createTime"`
	// 更新人
	Updator int64 `json:"updator"`
	// 更新时间
	UpdateTime types.Time `json:"updateTime"`
	// 乐观锁
	Version int `json:"version"`
	// 是否删除,1是,2否
	IsDelete int `json:"isDelete"`
}

// 创建组织请求结构体
type CreateOrgReq struct {
	// 组织名称
	OrgName string `json:"orgName"`
	// 补全个人姓名
	CreatorName *string `json:"creatorName"`
	// 是否要导入示例数据, 1：导入，2：不导入，默认不导入
	ImportSampleData *int `json:"importSampleData"`
	// 来源平台
	SourcePlatform *string `json:"sourcePlatform"`
	// 来源渠道
	SourceChannel *string `json:"sourceChannel"`
	// 所属行业id(选填)
	IndustryId *int64 `json:"industryId"`
	//组织规模（选填）
	Scale *string `json:"scale"`
}

// 删除文件夹请求结构体
type DeleteProjectFolderReq struct {
	// 文件夹id数组
	FolderIds []int64 `json:"folderIds"`
	// 项目id
	ProjectID int64 `json:"projectId"`
}

type DeleteProjectFolderResp struct {
	// 文件夹id数组
	FolderIds []int64 `json:"folderIds"`
}

type DeleteProjectResourceReq struct {
	// 文件id数组
	ResourceIds []int64 `json:"resourceIds"`
	// 文件夹id,只支持相同目录下的批量文件删除
	FolderID int64 `json:"folderId"`
	// 项目id
	ProjectID int64 `json:"projectId"`
}

type DeleteProjectResourceResp struct {
	// 文件id数组
	ResourceIds []int64 `json:"resourceIds"`
}

// 删除存放各类资源，其他业务表统一关联此表id请求结构体
type DeleteResourceReq struct {
	// 主键
	ID int64 `json:"id"`
}

// 删除请求结构体
type DeleteUserOrganizationReq struct {
	// 主键
	ID int64 `json:"id"`
}

// 部门结构体
type Department struct {
	// 主键
	ID int64 `json:"id"`
	// 组织id
	OrgID int64 `json:"orgId"`
	// 部门名称
	Name string `json:"name"`
	// 部门标识
	Code string `json:"code"`
	// 父部门id
	ParentID int64 `json:"parentId"`
	// 排序
	Sort int `json:"sort"`
	// 是否隐藏部门,1隐藏,2不隐藏
	IsHide int `json:"isHide"`
	// 来源渠道,
	SourceChannel string `json:"sourceChannel"`
	// 创建人
	Creator int64 `json:"creator"`
	// 创建时间
	CreateTime types.Time `json:"createTime"`
}

// 部门列表响应结构体
type DepartmentList struct {
	// 总数
	Total int64 `json:"total"`
	// 列表
	List []*Department `json:"list"`
}

type DepartmentListReq struct {
	// 父部门id
	ParentID *int64 `json:"parentId"`
	// 是否查询最上级部门, 如果是1则为true
	IsTop *int `json:"isTop"`
	// 是否显示隐藏的部门，如果是1则为true，默认不显示
	ShowHiding *int `json:"showHiding"`
	// 部门名称
	Name *string `json:"name"`
}

// 部门用户信息
type DepartmentMemberInfo struct {
	// id
	UserID int64 `json:"userId"`
	// 姓名
	Name string `json:"name"`
	// 姓名拼音
	NamePy *string `json:"namePy"`
	// 用户头像
	Avatar string `json:"avatar"`
	// 工号：企业下唯一
	EmplID string `json:"emplId"`
	// unionId： 开发者账号下唯一
	UnionID string `json:"unionId"`
	// 用户部门id
	DepartmentID int64 `json:"departmentId"`
}

type DepartmentMemberListReq struct {
	// 部门id
	DepartmentID *int64 `json:"departmentId"`
}

// 钉钉扫码登录返回结果
type DingAuthCodeResp struct {
	NickName  string              `json:"nickName"`
	OutUserID string              `json:"outUserId"`
	OrgList   []*OrgInfoForChosen `json:"orgList"`
}

type EveryPermission struct {
	// 权限组id
	PermissionID int64 `json:"permissionId"`
	// 修改后的操作项id
	OperationIds []int64 `json:"operationIds"`
}

// 飞书免登陆Code 登录验证请求结构体
type FeiShuAuthReq struct {
	// 免登code
	Code string `json:"code"`
	// 免登code类型，1: code2session, 2: oauth(默认为1)
	CodeType *int `json:"codeType"`
}

// 飞书免登陆Code 登录验证响应结构体
type FeiShuAuthResp struct {
	// 持久化登录信息的Token
	Token string `json:"token"`
	// 组织id
	OrgID int64 `json:"orgId"`
	// 组织名称
	OrgName string `json:"orgName"`
	// 组织code
	OrgCode string `json:"orgCode"`
	// 用户id
	UserID int64 `json:"userId"`
	// 用户姓名
	Name string `json:"name"`
}

// 文件夹结构体
type Folder struct {
	// 文件夹id
	ID int64 `json:"id"`
	// 组织id
	OrgID int64 `json:"orgId"`
	// 项目id
	ProjectID int64 `json:"projectId"`
	// 文件夹名
	Name string `json:"name"`
	// 父级文件夹id
	ParentID int64 `json:"parentId"`
	// 文件夹类型,0其他,1文档,2图片,3视频,4音频
	FileType int64 `json:"fileType"`
	// 文件路径
	Path string `json:"path"`
	// 创建人
	Creator int64 `json:"creator"`
	// 创建人中文名
	CreatorName string `json:"creatorName"`
	// 创建时间
	CreateTime types.Time `json:"createTime"`
	// 更新人
	Updator int64 `json:"updator"`
	// 更新时间
	UpdateTime types.Time `json:"updateTime"`
	// 乐观锁
	Version int `json:"version"`
	// 是否删除,1是,2否
	IsDelete int `json:"isDelete"`
}

// 文件夹列表相应结构体
type FolderList struct {
	Total int64     `json:"total"`
	List  []*Folder `json:"list"`
}

type FunctionConfigResp struct {
	// 功能
	FunctionCodes []string `json:"functionCodes"`
}

// 获取邀请码请求结构体
type GetInviteCodeReq struct {
	// 平台
	SourcePlatform *string `json:"sourcePlatform"`
}

// 获取邀请码响应结构体
type GetInviteCodeResp struct {
	// 邀请码
	InviteCode string `json:"inviteCode"`
	// 有效时长，单位：秒
	Expire int `json:"expire"`
}

// 获取邀请信息请求结构体
type GetInviteInfoReq struct {
	// 邀请code
	InviteCode string `json:"inviteCode"`
}

// 获取邀请信息响应结构体
type GetInviteInfoResp struct {
	// 组织id
	OrgID int64 `json:"orgId"`
	// 组织名
	OrgName string `json:"orgName"`
	// 邀请人id
	InviterID int64 `json:"inviterId"`
	// 邀请人姓名
	InviterName string `json:"inviterName"`
}

// 获取MQTT通道key请求结构体
type GetMQTTChannelKeyReq struct {
	// 通道类型：1、项目（任务，标签，工作栏），2、组织（成员）
	ChannelType int `json:"channelType"`
	// 通道类型为1时必传
	ProjectID *int64 `json:"projectId"`
}

// 获取MQTT通道key响应结构体
type GetMQTTChannelKeyResp struct {
	// 连接地址
	Address string `json:"address"`
	// host
	Host string `json:"host"`
	// port
	Port *int `json:"port"`
	// 通道
	Channel string `json:"channel"`
	// 通道key
	Key string `json:"key"`
}

type GetPersonalPermissionInfoResp struct {
	Data map[string]interface{} `json:"Data"`
}

type IndustryListResp struct {
	List []*IndustryResp `json:"list"`
}

type IndustryResp struct {
	// 主键
	ID int64 `json:"id"`
	// 名字
	Name string `json:"name"`
	// 中文名
	Cname string `json:"cname"`
}

type InternalAuthResp struct {
	HasPermission interface{} `json:"hasPermission"`
}

// 获取JSApi签名请求结构体
type JsAPISignReq struct {
	// 类型:目前只支持:jsapi
	Type string `json:"type"`
	// 路由url
	URL string `json:"url"`
	// dingtalk企业id
	CorpID string `json:"corpId"`
}

// 获取JSApi签名响应结构体
type JsAPISignResp struct {
	// 应用代理id
	AgentID int64 `json:"agentId"`
	// 时间戳
	TimeStamp string `json:"timeStamp"`
	// 随机字符串
	NoceStr string `json:"noceStr"`
	// 签名
	Signature string `json:"signature"`
}

// 结构体
type Notice struct {
	// 主键
	ID int64 `json:"id"`
	// 组织id
	OrgID int64 `json:"orgId"`
	// 通知类型, 1项目通知,2组织通知,
	Type int `json:"type"`
	// 操作类型
	RelationType string `json:"relationType"`
	// 冗余信息
	Ext string `json:"ext"`
	// 项目id
	ProjectID int64 `json:"projectId"`
	// issueId
	IssueID int64 `json:"issueId"`
	// 关联动态id
	TrendsID int64 `json:"trendsId"`
	// 通知内容
	Content string `json:"content"`
	// 被通知人
	Noticer int64 `json:"noticer"`
	// 状态, 1未读,2已读
	Status int `json:"status"`
	// 创建人
	Creator int64 `json:"creator"`
	// 创建时间
	CreateTime types.Time `json:"createTime"`
	// 创建人信息
	CreatorInfo *UserIDInfo `json:"creatorInfo"`
	// 项目名称
	ProjectName string `json:"projectName"`
	// 任务名称
	IssueName string `json:"issueName"`
	// 父任务id（没有则为0）
	ParentIssueID int64 `json:"parentIssueId"`
}

// 通知条数
type NoticeCountResp struct {
	Total int64 `json:"total"`
}

// 列表响应结构体
type NoticeList struct {
	Total int64     `json:"total"`
	List  []*Notice `json:"list"`
}

type NoticeListReq struct {
	// 通知类型, 1项目通知,2组织通知,
	Type *int `json:"type"`
	// 是否是@我的相关notice(不传或传1表示普通通知，2表示@我的)
	IsCallMe *int `json:"isCallMe"`
	// 上次分页的最后一条id
	LastID *int64 `json:"lastId"`
	// 项目id
	ProjectID *int64 `json:"projectId"`
	// 任务id
	IssueID *int64 `json:"issueId"`
}

// 组织配置响应结构体
type OrgConfig struct {
	// id
	ID int64 `json:"id"`
	// 组织id
	OrgID int64 `json:"orgId"`
	// 付费级别1通用免费，2标准版
	PayLevel int `json:"payLevel"`
	// 付费开始时间
	PayStartTime types.Time `json:"payStartTime"`
	// 付费结束时间
	PayEndTime types.Time `json:"payEndTime"`
}

type OrgInfoForChosen struct {
	// 组织id
	ID int64 `json:"id"`
	// 组织名称
	Name string `json:"name"`
}

type OrgProjectMemberInfoResp struct {
	// 用户id
	UserID int64 `json:"userId"`
	// 外部用户id
	OutUserID string `json:"outUserId"`
	// 组织id
	OrgID int64 `json:"orgId"`
	// 外部组织id
	OutOrgID string `json:"outOrgId"`
	// 姓名
	Name string `json:"name"`
	// 姓名拼音（可能为空）
	NamePy *string `json:"namePy"`
	// 用户头像
	Avatar string `json:"avatar"`
	// 是否有外部信息
	HasOutInfo bool `json:"hasOutInfo"`
	// 是否有组织外部信息
	HasOrgOutInfo bool `json:"hasOrgOutInfo"`
	// 组织用户是否删除
	OrgUserIsDelete int `json:"orgUserIsDelete"`
	// 组织用户状态
	OrgUserStatus int `json:"orgUserStatus"`
	// 组织用户check状态
	OrgUserCheckStatus int `json:"orgUserCheckStatus"`
}

type OrgProjectMemberReq struct {
	// 项目id
	ProjectID int64 `json:"projectId"`
}

type OrgProjectMemberResp struct {
	Owner        *OrgProjectMemberInfoResp   `json:"owner"`
	Participants []*OrgProjectMemberInfoResp `json:"participants"`
	Follower     []*OrgProjectMemberInfoResp `json:"follower"`
	AllMembers   []*OrgProjectMemberInfoResp `json:"allMembers"`
}

// 列表请求结构体
type OrgUserListReq struct {
	// 审核状态,1待审核,2审核通过,3审核不过(成员管理取审核通过的，成员审核取待审核和审核不过的)
	CheckStatus []int `json:"checkStatus"`
	// 使用状态,1已使用,2未使用
	UseStatus *int `json:"useStatus"`
	// 企业用户状态, 1可用,2禁用
	Status *int `json:"status"`
	// 姓名
	Name *string `json:"name"`
}

type OrganizationInfoReq struct {
	// 组织id
	OrgID int64 `json:"orgId"`
}

// 组织设置入参
type OrganizationInfoResp struct {
	// 组织id
	OrgID int64 `json:"orgId"`
	// 组织名称
	OrgName string `json:"orgName"`
	// code
	Code string `json:"code"`
	// 组织网站
	WebSite string `json:"webSite"`
	// 所属行业
	IndustryID int64 `json:"industryId"`
	// 所属行业中文名
	IndustryName string `json:"industryName"`
	// 组织规模
	Scale string `json:"scale"`
	// 所在国家
	CountryID int64 `json:"countryId"`
	// 所在国家中文名
	CountryCname string `json:"countryCname"`
	// 所在省份
	ProvinceID int64 `json:"provinceId"`
	// 所在省份中文名
	ProvinceCname string `json:"provinceCname"`
	// 所在城市
	CityID int64 `json:"cityId"`
	// 所在城市中文名
	CityCname string `json:"cityCname"`
	// 组织地址
	Address string `json:"address"`
	// 组织logo地址
	LogoURL string `json:"logoUrl"`
	// 组织所有者
	Owner int64 `json:"owner"`
	// 负责人信息
	OwnerInfo *UserIDInfo `json:"ownerInfo"`
}

// 结构体
type OrganizationUser struct {
	// 主键
	ID int64 `json:"id"`
	// 组织id
	OrgID int64 `json:"orgId"`
	// 用户id
	UserID int64 `json:"userId"`
	// 审核状态,1待审核,2审核通过,3审核不过
	CheckStatus int `json:"checkStatus"`
	// 使用状态,1已使用,2未使用
	UseStatus int `json:"useStatus"`
	// 企业用户状态, 1可用,2禁用
	Status int `json:"status"`
	// 状态变更人id
	StatusChangerID int64 `json:"statusChangerId"`
	// 状态变更时间
	StatusChangeTime types.Time `json:"statusChangeTime"`
	// 审核人id
	AuditorID int64 `json:"auditorId"`
	// 审核时间
	AuditTime types.Time `json:"auditTime"`
	// 创建人
	Creator int64 `json:"creator"`
	// 创建时间
	CreateTime types.Time `json:"createTime"`
	// 更新人
	Updator int64 `json:"updator"`
	// 更新时间
	UpdateTime types.Time `json:"updateTime"`
	// 用户信息
	UserInfo *PersonalInfo `json:"userInfo"`
	// 审核人信息
	AuditorInfo *PersonalInfo `json:"auditorInfo"`
	// 用户角色
	UserRole *UserRoleInfo `json:"userRole"`
}

// Oss申请signUrl请求结构体
type OssApplySignURLReq struct {
	// 文件url
	URL string `json:"url"`
}

// Oss申请signUrl响应结构体
type OssApplySignURLResp struct {
	// signUrl
	SignURL string `json:"signUrl"`
}

// Oss Post Policy策略请求结构体
type OssPostPolicyReq struct {
	// 策略类型, 1: 项目封面，2：任务资源（需要callback）, 3：导入任务的excel， 4：项目文件（需要callback），5：兼容测试， 6:用户头像
	PolicyType int `json:"policyType"`
	// 如果policyType为1和2和3，那么projectId必传(创建场景传0)
	ProjectID *int64 `json:"projectId"`
	// 如果policyType为2，那么issueId必传
	IssueID *int64 `json:"issueId"`
	// 目录id, policy为4的时候必填
	FolderID *int64 `json:"folderId"`
}

// Oss Post Policy策略响应结构体
type OssPostPolicyResp struct {
	// policy
	Policy string `json:"policy"`
	// 签名
	Signature string `json:"signature"`
	// 文件上传目录
	Dir string `json:"dir"`
	// 有效期
	Expire string `json:"expire"`
	// access Id
	AccessID string `json:"accessId"`
	// Host
	Host string `json:"host"`
	// Region
	Region string `json:"region"`
	// bucket名称
	Bucket string `json:"bucket"`
	// 文件名
	FileName string `json:"fileName"`
	// 文件最大限制
	MaxFileSize int64 `json:"maxFileSize"`
	// callback回调，为空说明不需要回调
	Callback string `json:"callback"`
}

// 结构体
type Permission struct {
	// 主键
	ID int64 `json:"id"`
	// 组织id,应该是全局的,因此填0
	OrgID int64 `json:"orgId"`
	// 语言编号
	LangCode string `json:"langCode"`
	// 编号,仅支持大写英文字母
	Code string `json:"code"`
	// 名称
	Name string `json:"name"`
	// 父id
	ParentID int64 `json:"parentId"`
	// 权限项类型,1系统,2组织,3项目
	Type int `json:"type"`
	// 权限路径
	Path string `json:"path"`
	// 是否显示,1是,2否
	IsShow int `json:"isShow"`
	// 描述
	Remark string `json:"remark"`
	// 状态,  1可用,2禁用
	Status int `json:"status"`
	// 创建人
	Creator int64 `json:"creator"`
	// 创建时间
	CreateTime types.Time `json:"createTime"`
	// 更新人
	Updator int64 `json:"updator"`
	// 更新时间
	UpdateTime types.Time `json:"updateTime"`
}

// 列表响应结构体
type PermissionList struct {
	Total int64         `json:"total"`
	List  []*Permission `json:"list"`
}

// 结构体
type PermissionOperation struct {
	// 主键
	ID int64 `json:"id"`
	// 组织id,应该是全局的,因此填0
	OrgID int64 `json:"orgId"`
	// 权限项id
	PermissionID int64 `json:"permissionId"`
	// 语言编号
	LangCode string `json:"langCode"`
	// 名称
	Name string `json:"name"`
	// 操作编号,多个半角逗号分隔
	OperationCodes string `json:"operationCodes"`
	// 描述
	Remark string `json:"remark"`
	// 是否显示,1是,2否
	IsShow int `json:"isShow"`
	// 状态,  1可用,2禁用
	Status int `json:"status"`
	// 创建人
	Creator int64 `json:"creator"`
	// 创建时间
	CreateTime types.Time `json:"createTime"`
	// 更新人
	Updator int64 `json:"updator"`
	// 更新时间
	UpdateTime types.Time `json:"updateTime"`
}

// 列表响应结构体
type PermissionOperationList struct {
	Total int64                  `json:"total"`
	List  []*PermissionOperation `json:"list"`
}

type PermissionOperationListResp struct {
	// 权限项信息
	PermissionInfo *Permission `json:"permissionInfo"`
	// 权限操作项信息
	OperationList []*PermissionOperation `json:"operationList"`
	// 角色拥有的操作项权限id
	PermissionHave []int64 `json:"permissionHave"`
}

// 个人信息
type PersonalInfo struct {
	// 主键
	ID int64 `json:"id"`
	// 工号
	EmplID *string `json:"emplId"`
	// 组织id
	OrgID int64 `json:"orgId"`
	// 组织名称
	OrgName string `json:"orgName"`
	// 组织code
	OrgCode string `json:"orgCode"`
	// 名称
	Name string `json:"name"`
	// 第三方名称
	ThirdName string `json:"thirdName"`
	// 登录名
	LoginName string `json:"loginName"`
	// 登录名编辑次数
	LoginNameEditCount int `json:"loginNameEditCount"`
	// 邮箱
	Email string `json:"email"`
	// 电话
	Mobile string `json:"mobile"`
	// 生日
	Birthday types.Time `json:"birthday"`
	// 性别
	Sex int `json:"sex"`
	// 剩余使用时长
	Rimanente int `json:"rimanente"`
	// 付费等级
	Level int `json:"level"`
	// 付费等级名
	LevelName string `json:"levelName"`
	// 头像
	Avatar string `json:"avatar"`
	// 来源
	SourceChannel string `json:"sourceChannel"`
	// 语言
	Language string `json:"language"`
	// 座右铭
	Motto string `json:"motto"`
	// 上次登录ip
	LastLoginIP string `json:"lastLoginIp"`
	// 上次登录时间
	LastLoginTime types.Time `json:"lastLoginTime"`
	// 登录失败次数
	LoginFailCount int `json:"loginFailCount"`
	// 创建时间
	CreateTime types.Time `json:"createTime"`
	// 更新时间
	UpdateTime types.Time `json:"updateTime"`
	// 密码是否设置过(1已设置0未设置)
	PasswordSet int `json:"passwordSet"`
	// 是否需要提醒（1需要2不需要）
	RemindBindPhone int `json:"remindBindPhone"`
	// 是否是超管
	IsAdmin bool `json:"isAdmin"`
	// 是否是管理员
	IsManager bool `json:"isManager"`
	// 权限
	Functions []string `json:"functions"`
}

type ProjectChatListReq struct {
	// 每页数量(不传默认10条)
	PageSize *int64 `json:"pageSize"`
	// 项目id
	ProjectID int64 `json:"projectId"`
	// 上次分页最后一条关联id（不传默认第一页）
	LastRelationID *int64 `json:"lastRelationId"`
	// 搜索内容
	Name *string `json:"name"`
}

type ProjectFolderReq struct {
	// 父文件夹id
	ParentID *int64 `json:"parentId"`
	// 项目id
	ProjectID int64 `json:"projectId"`
}

type ProjectResourceReq struct {
	// 文件夹id
	FolderID int64 `json:"folderId"`
	// 项目id
	ProjectID int64 `json:"projectId"`
}

// 阅读通知结构体
type ReadNoticeReq struct {
	// 主键
	ID int64 `json:"id"`
}

// 移除组织
type RemoveOrgMemberReq struct {
	// 要移除的组织成员列表
	MemberIds []int64 `json:"memberIds"`
}

// 存放各类资源，其他业务表统一关联此表id结构体
type Resource struct {
	// 主键
	ID int64 `json:"id"`
	// 组织id
	OrgID int64 `json:"orgId"`
	// host
	Host string `json:"host"`
	// 路径
	Path string `json:"path"`
	// 缩略图路径
	PathCompressed string `json:"pathCompressed"`
	// 文件名
	Name string `json:"name"`
	// 存储类型,1：本地，2：oss,3.钉盘
	Type int `json:"type"`
	// 文件大小
	Size int64 `json:"size"`
	// 创建人姓名
	CreatorName string `json:"creatorName"`
	// 文件后缀
	Suffix string `json:"suffix"`
	// 文件的md5
	Md5 string `json:"md5"`
	// 文件类型
	FileType int `json:"fileType"`
	// 创建人
	Creator int64 `json:"creator"`
	// 创建时间
	CreateTime types.Time `json:"createTime"`
	// 更新人
	Updator int64 `json:"updator"`
	// 更新时间
	UpdateTime types.Time `json:"updateTime"`
	// 乐观锁
	Version int `json:"version"`
	// 是否删除,1是,2否
	IsDelete int `json:"isDelete"`
}

// 存放各类资源，其他业务表统一关联此表id列表响应结构体
type ResourceList struct {
	Total int64       `json:"total"`
	List  []*Resource `json:"list"`
}

// 结构体
type Role struct {
	// 主键
	ID int64 `json:"id"`
	// 组织id,全局为0
	OrgID int64 `json:"orgId"`
	// 名称
	Name string `json:"name"`
	// 描述
	Remark string `json:"remark"`
	// 角色分组
	RoleGroupID int64 `json:"roleGroupId"`
	// 状态,  1可用,2禁用
	Status int `json:"status"`
	// 创建人
	Creator int64 `json:"creator"`
	// 创建时间
	CreateTime types.Time `json:"createTime"`
	// 更新人
	Updator int64 `json:"updator"`
	// 更新时间
	UpdateTime types.Time `json:"updateTime"`
}

// 发送各种验证码请求结构体
type SendAuthCodeReq struct {
	// 验证方式: 1: 登录验证码，2：注册验证码，3：修改密码验证码，4：找回密码验证码，5：绑定验证码, 6：解绑验证码，7更换管理员发送短信。
	AuthType int `json:"authType"`
	// 地址类型: 1：手机号，2：邮箱
	AddressType int `json:"addressType"`
	// 联系地址，根据地址类型区分手机号或者邮箱
	Address string `json:"address"`
	// 验证码id
	CaptchaID *string `json:"captchaId"`
	// 输入的验证码
	CaptchaPassword *string `json:"captchaPassword"`
}

// 发送短信登录验证码请求结构体
type SendSmsLoginCodeReq struct {
	// 手机号
	PhoneNumber string `json:"phoneNumber"`
	// 验证码id
	CaptchaID *string `json:"captchaId"`
	// 输入的验证码
	CaptchaPassword *string `json:"captchaPassword"`
}

type StatData struct {
	IssueCount             int `json:"issueCount"`
	IssueWaitCount         int `json:"issueWaitCount"`
	IssueRunningCount      int `json:"issueRunningCount"`
	IssueEndCount          int `json:"issueEndCount"`
	StoryPointCount        int `json:"storyPointCount"`
	StoryPointWaitCount    int `json:"storyPointWaitCount"`
	StoryPointRunningCount int `json:"storyPointRunningCount"`
	StoryPointEndCount     int `json:"storyPointEndCount"`
}

type StatExtResp struct {
	Issue *StatIssueExt `json:"issue"`
}

type StatIssueExt struct {
	Data *interface{} `json:"data"`
}

type SwitchUserOrganizationReq struct {
	// 组织id
	OrgID int64 `json:"orgId"`
}

type TransferOrgOwnerReq struct {
	OwnerID int64 `json:"ownerId"`
}

type UnrelatedChatListReq struct {
	// 每页数量(不传默认10条)
	PageSize *int64 `json:"pageSize"`
	// 项目id
	ProjectID int64 `json:"projectId"`
	// 上次分页最后一条外部群聊id（不传默认第一页）
	LastOutChatID *string `json:"lastOutChatId"`
	// 搜索内容
	Name *string `json:"name"`
}

// 更新接入应用信息请求结构体
type UpdateAppInfoReq struct {
	// 主键
	ID int64 `json:"id"`
	// 名称
	Name string `json:"name"`
	// 应用编号
	Code string `json:"code"`
	// 秘钥1
	Secret1 string `json:"secret1"`
	// 秘钥2
	Secret2 string `json:"secret2"`
	// 负责人
	Owner string `json:"owner"`
	// 审核状态,1待审核,2审核通过,3审核未通过
	CheckStatus int `json:"checkStatus"`
	// 状态,  1可用,2禁用
	Status int `json:"status"`
	// 创建人
	Creator int64 `json:"creator"`
	// 创建时间
	CreateTime types.Time `json:"createTime"`
	// 更新人
	Updator int64 `json:"updator"`
	// 更新时间
	UpdateTime types.Time `json:"updateTime"`
	// 乐观锁
	Version int `json:"version"`
	// 是否删除,1是,2否
	IsDelete int `json:"isDelete"`
}

// 更新部门请求结构体
type UpdateDepartmentReq struct {
	// 主键
	ID int64 `json:"id"`
	// 组织id
	OrgID int64 `json:"orgId"`
	// 部门名称
	Name string `json:"name"`
	// 部门标识
	Code string `json:"code"`
	// 父部门id
	ParentID int64 `json:"parentId"`
	// 排序
	Sort int `json:"sort"`
	// 是否隐藏部门,1隐藏,2不隐藏
	IsHide int `json:"isHide"`
	// 来源渠道,
	SourceChannel string `json:"sourceChannel"`
	// 状态, 1可用,2禁用
	Status int `json:"status"`
	// 创建人
	Creator int64 `json:"creator"`
	// 创建时间
	CreateTime types.Time `json:"createTime"`
	// 更新人
	Updator int64 `json:"updator"`
	// 更新时间
	UpdateTime types.Time `json:"updateTime"`
	// 乐观锁
	Version int `json:"version"`
	// 是否删除,1是,2否
	IsDelete int `json:"isDelete"`
}

type UpdateFunctionConfigReq struct {
	// 功能
	FunctionCodes []string `json:"functionCodes"`
}

// 修改组织成员审核状态请求结构体
type UpdateOrgMemberCheckStatusReq struct {
	// 要修改的组织成员列表
	MemberIds []int64 `json:"memberIds"`
	// 审核状态, 1待审核,2审核通过,3审核不过
	CheckStatus int `json:"checkStatus"`
}

// 修改组织成员状态请求结构体
type UpdateOrgMemberStatusReq struct {
	// 要修改的组织成员列表
	MemberIds []int64 `json:"memberIds"`
	// 状态,  1可用,2禁用
	Status int `json:"status"`
}

// 组织设置入参
type UpdateOrganizationSettingsReq struct {
	// 组织id
	OrgID int64 `json:"orgId"`
	// 组织名称
	OrgName string `json:"orgName"`
	// 组织code
	Code *string `json:"code"`
	// 所属行业
	IndustryID *int64 `json:"industryId"`
	// 组织规模
	Scale *string `json:"scale"`
	// 所在国家
	CountryID *int64 `json:"countryId"`
	// 所在省份
	ProvinceID *int64 `json:"provinceId"`
	// 所在城市
	CityID *int64 `json:"cityId"`
	// 组织地址
	Address *string `json:"address"`
	// 组织logo地址
	LogoURL *string `json:"logoUrl"`
	// 组织所有者
	Owner *int64 `json:"owner"`
	// 变动的字段列表
	UpdateFields []string `json:"updateFields"`
}

// 更新请求结构体
type UpdatePermissionOperationReq struct {
	// 主键
	ID int64 `json:"id"`
	// 组织id,应该是全局的,因此填0
	OrgID int64 `json:"orgId"`
	// 权限项id
	PermissionID int64 `json:"permissionId"`
	// 语言编号
	LangCode string `json:"langCode"`
	// 名称
	Name string `json:"name"`
	// 操作编号,多个半角逗号分隔
	OperationCodes string `json:"operationCodes"`
	// 描述
	Remark string `json:"remark"`
	// 是否显示,1是,2否
	IsShow int `json:"isShow"`
	// 状态,  1可用,2禁用
	Status int `json:"status"`
	// 创建人
	Creator int64 `json:"creator"`
	// 创建时间
	CreateTime types.Time `json:"createTime"`
	// 更新人
	Updator int64 `json:"updator"`
	// 更新时间
	UpdateTime types.Time `json:"updateTime"`
	// 乐观锁
	Version int `json:"version"`
	// 是否删除,1是,2否
	IsDelete int `json:"isDelete"`
}

// 更新请求结构体
type UpdatePermissionReq struct {
	// 主键
	ID int64 `json:"id"`
	// 组织id,应该是全局的,因此填0
	OrgID int64 `json:"orgId"`
	// 语言编号
	LangCode string `json:"langCode"`
	// 编号,仅支持大写英文字母
	Code string `json:"code"`
	// 名称
	Name string `json:"name"`
	// 父id
	ParentID int64 `json:"parentId"`
	// 权限项类型,1系统,2组织,3项目
	Type int `json:"type"`
	// 权限路径
	Path string `json:"path"`
	// 是否显示,1是,2否
	IsShow int `json:"isShow"`
	// 描述
	Remark string `json:"remark"`
	// 状态,  1可用,2禁用
	Status int `json:"status"`
	// 创建人
	Creator int64 `json:"creator"`
	// 创建时间
	CreateTime types.Time `json:"createTime"`
	// 更新人
	Updator int64 `json:"updator"`
	// 更新时间
	UpdateTime types.Time `json:"updateTime"`
	// 乐观锁
	Version int `json:"version"`
	// 是否删除,1是,2否
	IsDelete int `json:"isDelete"`
}

// 更新文件夹请求结构体
type UpdateProjectFolderReq struct {
	// 文件夹id
	FolderID int64 `json:"folderId"`
	// 项目id
	ProjectID int64 `json:"projectId"`
	// 文件夹名
	Name *string `json:"name"`
	// 父级文件夹id
	ParentID *int64 `json:"parentId"`
	// 文件夹类型,0其他,1文档,2图片,3视频,4音频
	FileType *int64 `json:"fileType"`
	// 变动的字段列表
	UpdateFields []string `json:"updateFields"`
}

type UpdateProjectFolderResp struct {
	// 文件夹id
	FolderID int64 `json:"folderId"`
}

type UpdateProjectResourceFolderReq struct {
	// 当前文件夹id
	CurrentFolderID int64 `json:"currentFolderId"`
	// 目标文件夹id
	TargetFolderID int64 `json:"targetFolderId"`
	// 文件id数组
	ResourceIds []int64 `json:"resourceIds"`
	// 项目id
	ProjectID int64 `json:"projectId"`
}

type UpdateProjectResourceFolderResp struct {
	// 文件id数组
	ResourceIds []int64 `json:"resourceIds"`
}

type UpdateProjectResourceNameReq struct {
	// 文件id
	ResourceID int64 `json:"resourceId"`
	// 项目id
	ProjectID int64 `json:"projectId"`
	// 文件名
	FileName *string `json:"fileName"`
	// 文件后缀
	FileSuffix *string `json:"fileSuffix"`
	// 修改项
	UpdateFields []string `json:"updateFields"`
}

type UpdateRelateChat struct {
	// 项目id
	ProjectID int64 `json:"projectId"`
	// 群聊外部id
	OutChatIds []string `json:"outChatIds"`
}

// 更新存放各类资源，其他业务表统一关联此表id请求结构体
type UpdateResourceReq struct {
	// 主键
	ID int64 `json:"id"`
	// 组织id
	OrgID int64 `json:"orgId"`
	// 路径
	Path string `json:"path"`
	// 文件名
	Name string `json:"name"`
	// 存储类型,1：本地，2：oss,3.钉盘
	Type int `json:"type"`
	// 文件后缀
	Suffix string `json:"suffix"`
	// 文件的md5
	Md5 string `json:"md5"`
	// 文件大小
	Size int64 `json:"size"`
	// 创建人
	Creator int64 `json:"creator"`
	// 创建时间
	CreateTime types.Time `json:"createTime"`
	// 更新人
	Updator int64 `json:"updator"`
	// 更新时间
	UpdateTime types.Time `json:"updateTime"`
	// 乐观锁
	Version int `json:"version"`
	// 是否删除,1是,2否
	IsDelete int `json:"isDelete"`
}

// 更新角色操作权限
type UpdateRolePermissionOperationReq struct {
	// 角色id
	RoleID int64 `json:"roleId"`
	// 项目id
	ProjectID *int64 `json:"projectId"`
	// 所有涉及到的更改的权限组
	UpdatePermissions []*EveryPermission `json:"updatePermissions"`
}

// 更新用户配置请求结构体
type UpdateUserConfigReq struct {
	// 主键
	ID int64 `json:"id"`
	// 个人日报开启状态, 2否, 1是
	DailyReportMessageStatus int `json:"dailyReportMessageStatus"`
	// 我负责的 2否, 1是
	OwnerRangeStatus int `json:"ownerRangeStatus"`
	// 我参与的, 2否, 1是
	ParticipantRangeStatus int `json:"participantRangeStatus"`
	// 我关注的, 2否, 1是
	AttentionRangeStatus int `json:"attentionRangeStatus"`
	// 我创建的, 2否, 1是
	CreateRangeStatus int `json:"createRangeStatus"`
	// 任务提醒状态 2否, 1是
	RemindMessageStatus int `json:"remindMessageStatus"`
	// 评论和at我的通知
	CommentAtMessageStatus int `json:"commentAtMessageStatus"`
	// 任务更新状态, 2否, 1是
	ModifyMessageStatus int `json:"modifyMessageStatus"`
	// 任务关联动态, 2否, 1是
	RelationMessageStatus int `json:"relationMessageStatus"`
	// 项目日报开启状态, 2否, 1是
	DailyProjectReportMessageStatus int `json:"dailyProjectReportMessageStatus"`
}

// 更新用户配置响应结构体
type UpdateUserConfigResp struct {
	// 主键
	ID int64 `json:"id"`
}

// 更新用户默认项目配置请求结构体
type UpdateUserDefaultProjectConfigReq struct {
	// 默认项目id, 机器人创建项目的时候会选用这个项目
	DefaultProjectID int64 `json:"defaultProjectId"`
	// 默认工作栏id
	DefaultProjectObjectTypeID *int64 `json:"defaultProjectObjectTypeId"`
}

// 更改用户个人信息
type UpdateUserInfoReq struct {
	// 姓名
	Name *string `json:"name"`
	// 性别
	Sex *int `json:"sex"`
	// 用户头像
	Avatar *string `json:"avatar"`
	// 生日
	Birthday *types.Time `json:"birthday"`
	// 是否需要提醒绑定手机号
	RemindBindPhone *int `json:"remindBindPhone"`
	// 变动的字段列表
	UpdateFields []string `json:"updateFields"`
}

type UpdateUserOrgRoleReq struct {
	// 用户id
	UserID int64 `json:"userId"`
	// 修改后的角色id
	RoleID int64 `json:"roleId"`
	// 项目Id
	ProjectID *int64 `json:"projectId"`
}

// 更新请求结构体
type UpdateUserOrganizationReq struct {
	// 主键
	ID int64 `json:"id"`
	// 组织id
	OrgID int64 `json:"orgId"`
	// 用户id
	UserID int64 `json:"userId"`
	// 审核状态,1待审核,2审核通过,3审核不过
	CheckStatus int `json:"checkStatus"`
	// 使用状态,1已使用,2未使用
	UseStatus int `json:"useStatus"`
	// 企业用户状态, 1可用,2禁用
	Status int `json:"status"`
	// 状态变更人id
	StatusChangerID int64 `json:"statusChangerId"`
	// 状态变更时间
	StatusChangeTime types.Time `json:"statusChangeTime"`
	// 审核人id
	AuditorID int64 `json:"auditorId"`
	// 审核时间
	AuditTime types.Time `json:"auditTime"`
	// 创建人
	Creator int64 `json:"creator"`
	// 创建时间
	CreateTime types.Time `json:"createTime"`
	// 更新人
	Updator int64 `json:"updator"`
	// 更新时间
	UpdateTime types.Time `json:"updateTime"`
	// 乐观锁
	Version int `json:"version"`
	// 是否删除,1是,2否
	IsDelete int `json:"isDelete"`
}

// 更新用户pc配置请求结构体
type UpdateUserPcConfigReq struct {
	// pc桌面通知开关状态, 2否, 1是
	PcNoticeOpenStatus *int `json:"pcNoticeOpenStatus"`
	// pc任务提醒状态, 2否, 1是
	PcIssueRemindMessageStatus *int `json:"pcIssueRemindMessageStatus"`
	// pc组织相关推送状态, 2否, 1是
	PcOrgMessageStatus *int `json:"pcOrgMessageStatus"`
	// pc项目相关推送状态, 2否, 1是
	PcProjectMessageStatus *int `json:"pcProjectMessageStatus"`
	// pc评论相关推送状态, 2否, 1是
	PcCommentAtMessageStatus *int `json:"pcCommentAtMessageStatus"`
	// 变动的字段列表
	UpdateFields []string `json:"updateFields"`
}

// 用户配置信息结构体
type UserConfig struct {
	// 主键
	ID int64 `json:"id"`
	// 个人日报开启状态, 2否, 1是
	DailyReportMessageStatus int `json:"dailyReportMessageStatus"`
	// 我负责的 2否, 1是
	OwnerRangeStatus int `json:"ownerRangeStatus"`
	// 我参与的, 2否, 1是
	ParticipantRangeStatus int `json:"participantRangeStatus"`
	// 我关注的, 2否, 1是
	AttentionRangeStatus int `json:"attentionRangeStatus"`
	// 我创建的, 2否, 1是
	CreateRangeStatus int `json:"createRangeStatus"`
	// 任务提醒状态 2否, 1是
	RemindMessageStatus int `json:"remindMessageStatus"`
	// 评论和at我的通知
	CommentAtMessageStatus int `json:"commentAtMessageStatus"`
	// 任务更新状态, 2否, 1是
	ModifyMessageStatus int `json:"modifyMessageStatus"`
	// 任务关联动态, 2否, 1是
	RelationMessageStatus int `json:"relationMessageStatus"`
	// 项目日报开启状态, 2  否 1:是
	DailyProjectReportMessageStatus int `json:"dailyProjectReportMessageStatus"`
	// 默认项目id, 机器人创建项目的时候会选用这个项目
	DefaultProjectID int64 `json:"defaultProjectId"`
	// 默认工作栏
	DefaultProjectObjectTypeID int64 `json:"defaultProjectObjectTypeId"`
	// pc桌面通知开关状态, 2否, 1是
	PcNoticeOpenStatus int `json:"pcNoticeOpenStatus"`
	// pc任务提醒状态, 2否, 1是
	PcIssueRemindMessageStatus int `json:"pcIssueRemindMessageStatus"`
	// pc组织相关推送状态, 2否, 1是
	PcOrgMessageStatus int `json:"pcOrgMessageStatus"`
	// pc项目相关推送状态, 2否, 1是
	PcProjectMessageStatus int `json:"pcProjectMessageStatus"`
	// pc评论相关推送状态, 2否, 1是
	PcCommentAtMessageStatus int `json:"pcCommentAtMessageStatus"`
}

// 用户id信息
type UserIDInfo struct {
	// 用户id
	ID int64 `json:"id"`
	// 用户id
	UserID int64 `json:"userId"`
	// 用户名称
	Name string `json:"name"`
	// 用户拼音
	NamePy string `json:"namePy"`
	// 用户头像
	Avatar string `json:"avatar"`
	// 工号：企业下唯一
	EmplID string `json:"emplId"`
	// unionId： 开发者账号下唯一(暂时废弃，返回空)
	UnionID string `json:"unionId"`
	// 是否已被删除，为true则代表被组织移除
	IsDeleted bool `json:"isDeleted"`
	// 是否已被禁用, 为true则代表被组织禁用
	IsDisabled bool `json:"isDisabled"`
}

// 用户登录请求结构体
type UserLoginReq struct {
	// 登录类型: 1、短信验证码登录，2、账号密码登录，3、邮箱验证码登录
	LoginType int `json:"loginType"`
	// 登录类型为1时，loginName为手机号； 登录类型为3时，loginName为邮箱
	LoginName string `json:"loginName"`
	// 登录类型为2时，密码必传
	Password string `json:"password"`
	// 验证码
	AuthCode string `json:"authCode"`
	// 注册时可以带上名字
	Name string `json:"name"`
	// 邀请码, 邀请注册时必填
	InviteCode string `json:"inviteCode"`
	// 来源通道
	SourceChannel string `json:"sourceChannel"`
	// 平台
	SourcePlatform string `json:"sourcePlatform"`
}

// 用户登录响应结构体
type UserLoginResp struct {
	// 用户token
	Token string `json:"token"`
	// 用户id
	UserID int64 `json:"userId"`
	// 组织id
	OrgID int64 `json:"orgId"`
	// 组织名称
	OrgName string `json:"orgName"`
	// 组织code
	OrgCode string `json:"orgCode"`
	// 用户名称
	Name string `json:"name"`
	// 头像
	Avatar string `json:"avatar"`
	// 是否需要创建组织
	NeedInitOrg bool `json:"needInitOrg"`
}

// 用户组织列表响应结构体
type UserOrganization struct {
	// 组织id
	ID int64 `json:"id"`
	// 组织名称
	Name string `json:"name"`
	// 组织code
	Code string `json:"code"`
	// 组织网站
	WebSite string `json:"webSite"`
	// 所属行业
	IndustryID int64 `json:"industryId"`
	// 组织规模
	Scale string `json:"scale"`
	// 来源平台
	SourcePlatform string `json:"sourcePlatform"`
	// 来源渠道
	SourceChannel string `json:"sourceChannel"`
	// 所在国家
	CountryID int64 `json:"countryId"`
	// 所在省份
	ProvinceID int64 `json:"provinceId"`
	// 所在城市
	CityID int64 `json:"cityId"`
	// 组织地址
	Address string `json:"address"`
	// 组织logo地址
	LogoURL string `json:"logoUrl"`
	// 组织标识
	ResorceID int64 `json:"resorceId"`
	// 组织所有人,创建时默认为创建人
	Owner int64 `json:"owner"`
	// 企业是否认证
	IsAuthenticated int `json:"IsAuthenticated"`
	// 描述
	Remark string `json:"remark"`
	// 是否展示
	IsShow int `json:"isShow"`
	// 是否删除,1是,2否
	IsDelete *int `json:"isDelete"`
	// 对于该用户组织是否可用（1是2否）
	OrgIsEnabled *int `json:"OrgIsEnabled"`
	// 组织可用功能
	Functions []string `json:"functions"`
}

// 列表响应结构体
type UserOrganizationList struct {
	Total int64               `json:"total"`
	List  []*OrganizationUser `json:"list"`
}

type UserOrganizationListResp struct {
	// 用户组织列表
	List []*UserOrganization `json:"list"`
}

// 用户注册响应结构体
type UserRegisterResp struct {
	// 用户token
	Token string `json:"token"`
}

type UserRoleInfo struct {
	// 角色id
	ID int64 `json:"id"`
	// 角色名称
	Name string `json:"name"`
	// 角色lang_code
	LangCode string `json:"langCode"`
}
